#!/usr/bin/python
import tempfile
import os
from twisted.python import log

logfd, name = tempfile.mkstemp(suffix='.log', prefix='sepiida-agent-')
logf = os.fdopen(logfd, 'wb')
log.startLogging(logf)

from sepiida.agent import config
config.reload()
cfg = config.get()

if cfg.getboolean('Agent', 'log debug'):
    def log_debug(*args, **kwargs):
        log.msg(*args, **kwargs)
else:
    def log_debug(*args, **kwargs):
        pass
log.debug = log_debug

from sepiida.agent import protocol, userinfo
from twisted.internet import reactor, stdio

def connectionLost(reason):
    try:
        reactor.stop()
    except:
        pass

ap = protocol.AgentProtocol()
ap.connectionLost = connectionLost
s = stdio.StandardIO(ap)
reactor.run()
